# Generated by Django 4.2.13 on 2024-07-10 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullName",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Полное имя"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=50, verbose_name="Электронная почта"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
            },
        ),
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        upload_to=users.models.avatar_directory_path,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Описание"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatar",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аватар пользователя",
            },
        ),
    ]
