# Generated by Django 4.2.13 on 2024-07-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=16, verbose_name="Номер карты")),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Имя владельца карты"
                    ),
                ),
                (
                    "month",
                    models.CharField(max_length=2, verbose_name="Месяц на карте"),
                ),
                ("year", models.CharField(max_length=4, verbose_name="Год на карте")),
                ("code", models.CharField(max_length=3, verbose_name="CVV")),
            ],
        ),
    ]
