# Generated by Django 4.2.13 on 2024-06-20 17:34

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.categories",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=100, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="freeDelivery",
            field=models.BooleanField(
                default=False, verbose_name="Бесплатная доставка"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fullDescription",
            field=models.TextField(blank=True, verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="Рейтинг"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(blank=True, max_length=100, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="src",
            field=models.ImageField(
                upload_to=catalog.models.product_images_directory_path,
                verbose_name="Ссылка",
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="value",
            field=models.CharField(max_length=100, verbose_name="Значение"),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(default=0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Название"
            ),
        ),
    ]
