# Generated by Django 4.2.13 on 2024-06-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_product_category_alter_product_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="catalog.product"
            ),
        ),
    ]
