# Generated by Django 4.2.13 on 2024-06-20 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_product_options_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
    ]
