# Generated by Django 4.2.13 on 2024-07-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_category_parent_categoryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited",
            field=models.BooleanField(
                default=False, verbose_name="Лимитированный товар"
            ),
        ),
    ]
