# Generated by Django 4.2.13 on 2024-07-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_product_limited"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salePrice",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Цена со скидкой",
                    ),
                ),
                ("dateFrom", models.DateField(verbose_name="Действует с")),
                ("dateTo", models.DateField(verbose_name="Дейсвтвует до")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="catalog.product",
                        verbose_name="Скидки",
                    ),
                ),
            ],
        ),
    ]
