# Generated by Django 4.2.13 on 2024-07-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_sale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="categoryimage",
            options={"verbose_name": "Изображение категории"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товара",
            },
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"verbose_name": "Скидка", "verbose_name_plural": "Скидки"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titul",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название баннера"
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banneer",
                        to="catalog.sale",
                        verbose_name="Баннер",
                    ),
                ),
            ],
        ),
    ]
