# Generated by Django 4.2.13 on 2024-07-22 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="author",
        ),
    ]
