# Generated by Django 4.2.13 on 2024-08-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_rename_user_review_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.EmailField(default="example@google.com", max_length=254, verbose_name="email"),
            preserve_default=False,
        ),
    ]
