# Generated by Django 4.2.13 on 2024-08-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_review_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
    ]
