# Generated by Django 4.2.13 on 2024-09-04 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_product_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"verbose_name": "Баннер", "verbose_name_plural": "Баннеры"},
        ),
    ]
