# Generated by Django 4.2.13 on 2024-07-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="basket",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_items",
                to="basket.basket",
            ),
            preserve_default=False,
        ),
    ]
